Cypress.Commands.add('signUpCheck', () => {
    cy.visit('/')
    cy.get('#signup')
    .should('have.text', 'Sign up')
        .and('not.be.disabled')
        .click()
    cy.get('h1')
    .should('have.text', 'Add User')
    cy.contains('p', 'Sign up to begin adding your contacts!') 
})